# Generated by Django 5.2.7 on 2025-10-30 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_auth', '0001_initial'),
        ('core_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectrole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core_tasks.project'),
        ),
        migrations.AddField(
            model_name='userprojectrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='core_auth.role'),
        ),
        migrations.AddField(
            model_name='userprojectrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userprojectrole',
            unique_together={('user', 'project')},
        ),
    ]
