# Generated by Django 5.2.7 on 2025-10-31 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0002_initial'),
        ('core_tasks', '0002_remove_project_team_project_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprojectrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='teamgroup',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='teamgroup',
            name='members',
        ),
        migrations.AlterUniqueTogether(
            name='userprojectrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprojectrole',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='userprojectrole',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userprojectrole',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_projects', 'Can view all projects'), ('manage_projects', 'Can create, edit, and delete projects'), ('view_all_tasks', 'Can view all tasks'), ('manage_tasks', 'Can create, edit, and delete tasks'), ('assign_tasks', 'Can assign tasks to users'), ('schedule_meetings', 'Can schedule meetings'), ('manage_meetings', 'Can edit and delete meetings'), ('request_approvals', 'Can request approvals'), ('approve_requests', 'Can approve/reject approval requests'), ('view_reports', 'Can view reports and analytics'), ('export_data', 'Can export data'), ('manage_users', 'Can manage users and permissions')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_bot_active',
            field=models.BooleanField(default=True, help_text='Whether user can access the bot'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('working_hours_start', models.TimeField(blank=True, null=True)),
                ('working_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='TeamGroup',
        ),
        migrations.DeleteModel(
            name='UserProjectRole',
        ),
    ]
